name: docker
on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'docker user name'
        required: true
        default: ''
      docker_password:
        description: 'docker user password'
        required: true
        default: ''
      version:
        description: 'version'
        required: true
        default: ''
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}
      - 
        name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.event.inputs.docker_username }}/proxypool:latest
            ${{ github.event.inputs.docker_username }}/proxypool:${{ github.event.inputs.version }}
